version: '3.4'

services:
  tpg_ioc:
    image: tidair/smurf-tpg-ioc:%%TPG_VERSION%%
    container_name: tpg_ioc
    volumes:
    - /data:/data
    network_mode: "host"
    environment:
    - location=${PWD}
    - EPICS_CA_ADDR_LIST=172.17.255.255
    security_opt:
    - "apparmor=docker-smurf"
    tty: true
    stdin_open: true
    logging:
      options:
        tag: tpg_ioc